name: 12a_58
braid: [-1, 4, -3, -3, 2, -1, 4, -1, 4, -3, 2, 2]
degree: 6
save_data: true
inversion:
  0: [-1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1,
    -1, -1]
threads: 24
