name: 12a_1246
braid: [1, 1, 1, -2, 1, 1, -2, -2, -2, 1, 1, -2]
degree: 6
save_data: true
inversion:
  0: [-1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1,
    -1, 1]
threads: 24
