name: 12n_35
braid: [-4, 3, -4, 3, 2, -1, 2, -1, 2, -3, -3, 2]
degree: 6
save_data: true
inversion:
  0: [1, -1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, -1, 1, 1, -1, 1, -1, 1, -1, 1, -1,
    1, -1]
threads: 24
