name: '10_145'
braid: [1, 3, -2, -1, -3, -2, -2, -1, -1, -3, -2]
degree: 6
save_data: true
inversion:
  0: [1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1,
    1, -1]
threads: 24
