name: 12a_70
braid: [-1, -3, -3, -3, -2, -2, -4, 3, -4, -4, 3, 2, -1, 2]
degree: 6
save_data: true
inversion:
  0: [1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, -1, 1, -1, -1, -1,
    -1, 1, -1, 1, 1, -1]
threads: 24
