name: 12n_45
braid: [-1, 2, 3, -1, -2, 3, 2, 4, 4, -3, 4, -3]
degree: 6
save_data: true
inversion:
  0: [-1, -1, 1, 1, 1, -1, -1, -1, -1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1,
    -1, 1, -1]
threads: 24
