name: 12n_879
braid: [-1, 2, -3, -1, 2, -3, 2, -3, -3, -2, -2, 3, 3]
degree: 6
save_data: true
inversion:
  0: [1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1, -1,
    -1, 1, 1, -1]
threads: 24
