name: 12a_298
braid: [1, -2, 3, -4, -2, 3, -4, 1, 1, -2, -2, -2]
degree: 6
save_data: true
inversion:
  0: [-1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1,
    -1, 1]
threads: 24
