name: 12a_245
braid: [1, -2, -3, -3, 4, -3, 2, -3, 2, 4, 3, 1, 1, -2]
degree: 6
save_data: true
inversion:
  0: [1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1,
    -1, -1, 1, 1, 1]
threads: 24
