name: 12a_331
braid: [-1, 2, -3, -4, -1, -2, -4, 3, -2, -4, -4, -4, 3, 3]
degree: 6
save_data: true
inversion:
  0: [1, -1, 1, 1, -1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1,
    -1, -1, -1, 1, 1, -1]
threads: 24
