name: 12a_699
braid: [-1, -3, -3, -4, -2, 3, -2, 3, 3, -4, 3, 2, -1, 2]
degree: 6
save_data: true
inversion:
  0: [-1, -1, -1, 1, -1, 1, -1, 1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1,
    -1, 1, 1, -1, 1, 1, -1]
threads: 24
