name: 12n_480
braid: [-1, 2, 3, -1, 3, -4, -2, 3, 2, -4, 2, -3]
degree: 6
save_data: true
inversion:
  0: [-1, -1, 1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, -1,
    -1, 1, -1]
threads: 24
