name: 12a_30
braid: [-1, 2, -1, 2, 3, -4, -4, 3, 3, 3, -4, -2, -2, -3]
degree: 6
save_data: true
inversion:
  0: [1, -1, 1, -1, -1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, -1, -1, -1, -1, 1, -1,
    1, -1, 1, -1, 1, 1, -1]
threads: 24
