name: 12n_7
braid: [-1, 2, 3, -1, 3, 2, -3, 4, -3, -3, -3, 4]
degree: 6
save_data: true
inversion:
  0: [1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1,
    1, -1]
threads: 24
