name: 12a_515
braid: [1, -2, 3, 4, 2, -3, 4, -3, 2, -3, 1, -3, 1, -2]
degree: 6
save_data: true
inversion:
  0: [1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1,
    -1, -1, 1, 1, 1]
threads: 24
