name: 12a_477
braid: [-1, 2, -3, 4, -5, 6, -1, 2, -3, 4, -5, 6]
degree: 6
save_data: true
inversion:
  0: [1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1,
    1, -1]
threads: 24
