name: 12n_346
braid: [1, -3, -3, 1, -2, -2, -3, -2, 1, 2, 2, 2, 2]
degree: 6
save_data: true
inversion:
  0: [-1, 1, -1, 1, 1, -1, 1, 1, -1, 1, -1, 1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1,
    -1, -1, -1, 1]
threads: 24
