name: 12n_627
braid: [1, 1, 2, 3, -1, 2, -1, -2, -2, 3, 3, -2, -2]
degree: 6
save_data: true
inversion:
  0: [-1, 1, -1, -1, 1, 1, -1, 1, -1, 1, -1, -1, -1, -1, -1, 1, -1, 1, -1, 1, 1, 1,
    -1, 1, 1, -1]
threads: 24
