name: 12a_458
braid: [-1, -3, 2, -3, 4, 2, -3, 2, -1, 4, -3, 2]
degree: 6
save_data: true
inversion:
  0: [-1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1,
    1, -1]
threads: 24
