name: 11n_91
braid: [1, -4, 3, -4, 3, -2, -1, -1, -3, -3, -3, -2]
degree: 6
save_data: true
inversion:
  0: [1, 1, -1, -1, 1, 1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, -1, -1,
    -1, -1]
threads: 24
