name: 12a_991
braid: [1, 4, -3, 2, -3, -3, 4, -3, -2, -2, -2, 1, -3, -2]
degree: 6
save_data: true
inversion:
  0: [1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, -1, -1, -1, -1, 1, -1, -1,
    1, -1, 1, 1, -1, 1]
threads: 24
